
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-courses-f25-03
owner: ucsb-cs156-f25
repo_name: proj-courses-f25-03
pull_requests: [{"author":{"id":"MDQ6VXNlcjU4NzU3Nzgz","is_bot":false,"login":"TOXICXUHUAN","name":""},"headRefName":"Dylan-AddFeedbackWhenCourseIsEmpty","number":41,"title":"add loading message and course not found when no courses","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-03/pull/41"},{"author":{"id":"MDQ6VXNlcjgwNjMwMDQx","is_bot":false,"login":"terryZhouqr","name":"terry"},"headRefName":"reintroduce_eslint_TZ","number":40,"title":"Reintroduce React Eslint Rules","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-03/pull/40"},{"author":{"id":"U_kgDOCM7fCA","is_bot":false,"login":"ChenchangWang1018","name":""},"headRefName":"Chenchang-#15","number":35,"title":"Remove SectionsTable Eslint Exception","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-03/pull/35"},{"author":{"id":"MDQ6VXNlcjgwNjMwMDQx","is_bot":false,"login":"terryZhouqr","name":"terry"},"headRefName":"remove_helper_function_TZ","number":34,"title":"Remove helper function tz","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-03/pull/34"},{"author":{"id":"MDQ6VXNlcjg3MjU4Mjc1","is_bot":false,"login":"adamw3455","name":""},"headRefName":"Fix-AdminJobs/UpdatesPage-Tests","number":33,"title":"Fix inconsistent test behavior for AdminJobsPage and AdminUpdatesPage","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-03/pull/33"},{"author":{"id":"U_kgDOClGZww","is_bot":false,"login":"JoshuaChu2004","name":""},"headRefName":"Joshua-CoursesDetailsPageLink","number":31,"title":"Joshua courses details page link","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-03/pull/31"},{"author":{"id":"MDQ6VXNlcjgwNjMwMDQx","is_bot":false,"login":"terryZhouqr","name":"terry"},"headRefName":"refactor_personal_schedual_TZ","number":29,"title":"Refactor Personal Schedule Details Page","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-03/pull/29"},{"author":{"id":"MDQ6VXNlcjU4NzU3Nzgz","is_bot":false,"login":"TOXICXUHUAN","name":""},"headRefName":"Dylan-LookupbyClassroomNumber","number":28,"title":"New dropdown with classrooms","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-03/pull/28"}]
