
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-courses-f25-03
owner: ucsb-cs156-f25
repo_name: proj-courses-f25-03
pull_requests: [{"author":{"id":"MDQ6VXNlcjg3MjU4Mjc1","is_bot":false,"login":"adamw3455","name":""},"headRefName":"Paginate-Job-Log-Table-Frontend","number":24,"title":"Paginate Job Log Table with search form, fix bug in job pagination enâ€¦","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-03/pull/24"}]
