
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-courses-f25-03
owner: ucsb-cs156-f25
repo_name: proj-courses-f25-03
pull_requests: [{"author":{"id":"MDQ6VXNlcjgwNjMwMDQx","is_bot":false,"login":"terryZhouqr","name":"terry"},"headRefName":"user-friendly-TZ","number":45,"title":"User friendly tz","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-03/pull/45"},{"author":{"id":"U_kgDOClGZww","is_bot":false,"login":"JoshuaChu2004","name":""},"headRefName":"Joshua-CoursesUserPaginationBackend","number":44,"title":"Joshua Add User Pagination Backend Endpoint","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-03/pull/44"},{"author":{"id":"U_kgDODf2SeQ","is_bot":false,"login":"tarang-netizen","name":""},"headRefName":"Tarang-Refactor-Csv-2","number":42,"title":"Tarang refactor csv 2","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-03/pull/42"},{"author":{"id":"MDQ6VXNlcjgwNjMwMDQx","is_bot":false,"login":"terryZhouqr","name":"terry"},"headRefName":"reintroduce_eslint_TZ","number":40,"title":"Reintroduce React Eslint Rules","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-03/pull/40"},{"author":{"id":"MDQ6VXNlcjgwNjMwMDQx","is_bot":false,"login":"terryZhouqr","name":"terry"},"headRefName":"refactor_personal_schedual_TZ","number":29,"title":"Refactor Personal Schedule Details Page","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-03/pull/29"}]
